export default {
    "index": {
        "title": "Introduction",
        "type": "page",
        "display": "hidden",
        "theme": {
            "layout": "full"
        }
    },
    "---1": {
        "type": "separator",
        "title": "Installation"
    },
    "installation": "Install Next.js",
    "install-tailwind": "Install Tailwind CSS",
    "add-utilities": "Add utilities",
    "cli": "CLI",
    "---2": {
        "type": "separator",
        "title": "Components"
    },
    "ai-input": "AI Input",
    "animated-tab-bar": "Animated Tab Bar",
    "apple-spotlight": "Apple Spotlight",
    "circle-menu": "Circle Menu",
    "creepy-button": "Creepy Button",
    "dialog-form": "Dialog Form",
    "eagle-vision": "Eagle Vision",
    "expandable-bento-grid": "Expandable Bento Grid",
    "flip-fade-text": "Flip Fade Text",
    "flip-scroll": "Flip Scroll",
    "flip-text": "Flip Text",
    "floating-navigation": "Floating Navigation",
    "flow-scroll": "Flow Scroll",
    "folder-preview": "Folder Preview",
    "glass-dock": "Dock",
    "glitch-text": "Glitch Text",
    "glow-border-card": "Glow Border Card",
    "glowing-effect": "Glowing Effect",
    "glowing-scroll-indicator": "Glowing Scroll Indicator",
    "horizontal-scroll": "Horizontal Scroll",
    "icon-wheel": "Icon Wheel",
    "image-pile": "Image Pile",
    "infinite-moving-cards": "Infinite Moving Cards",
    "interactive-book": "Interactive Book",
    "interest-picker": "Interest Picker",
    "jelly-loader": "Jelly Loader",
    "leave-rating": "Leave Rating",
    "light-lines": "Light Lines",
    "liquid-ocean": "Liquid Ocean",
    "liquid-text": "3D Displacement Text",
    "magnet-tabs": "Magnet Tabs",
    "mask-cursor-effect": "Mask Cursor Effect",
    "masked-avatars": "Masked Avatars",
    "masonry-grid": "Masonry Grid",
    "neumorphism-3d-button": "Neumorphism 3D Button",
    "otp-input": "OTP Input",
    "perspective-grid": "Perspective Grid",
    "photo-gallery": "Photo Gallery",
    "pixelated-carousel": "Pixelated Carousel",
    "pixelated-image-trail": "Pixelated Image Trail",
    "retro-pixel-button": "Retro Pixel Button",
    "rolling-ball-scroll-indicator": "Rolling Ball Scroll Indicator",
    "rubik-cube": "Rubik Cube",
    "scroll-effect": "Scroll Effect",
    "sine-wave": "Sine Wave",
    "social-flip-button": "Social Flip Button",
    "spotlight-navbar": "Spotlight Navbar",
    "stacked-logos": "Stacked Logos",
    "staggered-grid": "Staggered Grid",
    "testimonials-card": "Testimonials Card",
    "trading-card": "Trading Card"
}
